apiVersion: v1
kind: Service
metadata:
  name: stt-workbench-backend
  labels:
    app.kubernetes.io/name: stt-workbench-backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app.kubernetes.io/name: stt-workbench-backend
---
apiVersion: v1
kind: Service
metadata:
  name: stt-workbench-frontend
  labels:
    app.kubernetes.io/name: stt-workbench-frontend
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: stt-workbench-frontend
