apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stag
resources:
  - ../../base
images:
  - name: stt-workbench-backend
    newName: gcr.io/media17-streaming/stt/workbench-backend
    newTag: 8f34159487804355c2c16cca931d2da7100c4f28
  - name: stt-workbench-frontend
    newName: gcr.io/media17-streaming/stt/workbench-frontend
    newTag: 8f34159487804355c2c16cca931d2da7100c4f28
