apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stag
resources:
  - ../../base
images:
  - name: stt-workbench-backend
    newName: gcr.io/media17-streaming/stt/workbench-backend
    newTag: stag
  - name: stt-workbench-frontend
    newName: gcr.io/media17-streaming/stt/workbench-frontend
    newTag: stag
